"""add sede_id to all tenant models

Revision ID: 074568f4cfb8
Revises: b4e0bae1abcd
Create Date: 2026-05-26 00:53:44.898410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '074568f4cfb8'
down_revision: Union[str, Sequence[str], None] = 'b4e0bae1abcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caja_movimientos', sa.Column('sede_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_caja_movimientos_sede_id'), 'caja_movimientos', ['sede_id'], unique=False)
    op.create_foreign_key(None, 'caja_movimientos', 'sedes', ['sede_id'], ['id'])
    op.add_column('cierres_caja', sa.Column('sede_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('uq_cierres_caja_clinica_fecha'), table_name='cierres_caja')
    op.create_index(op.f('ix_cierres_caja_sede_id'), 'cierres_caja', ['sede_id'], unique=False)
    op.create_unique_constraint('uq_cierres_caja_clinica_sede_fecha', 'cierres_caja', ['clinica_id', 'sede_id', 'fecha'])
    op.create_foreign_key(None, 'cierres_caja', 'sedes', ['sede_id'], ['id'])
    op.alter_column('clinicas', 'margen_global',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'50'"))
    op.add_column('comprobantes', sa.Column('sede_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comprobantes_sede_id'), 'comprobantes', ['sede_id'], unique=False)
    op.create_foreign_key(None, 'comprobantes', 'sedes', ['sede_id'], ['id'])
    op.add_column('inv_compras', sa.Column('sede_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('uq_inv_compras_clinica_doc_numero'), table_name='inv_compras')
    op.create_index(op.f('ix_inv_compras_sede_id'), 'inv_compras', ['sede_id'], unique=False)
    op.create_unique_constraint('uq_inv_compras_clinica_sede_doc_numero', 'inv_compras', ['clinica_id', 'sede_id', 'tipo_doc', 'numero'])
    op.create_foreign_key(None, 'inv_compras', 'sedes', ['sede_id'], ['id'])
    op.add_column('inv_movimientos', sa.Column('sede_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inv_movimientos_sede_id'), 'inv_movimientos', ['sede_id'], unique=False)
    op.create_foreign_key(None, 'inv_movimientos', 'sedes', ['sede_id'], ['id'])
    op.add_column('pacientes', sa.Column('sede_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pacientes_sede_id'), 'pacientes', ['sede_id'], unique=False)
    op.create_foreign_key(None, 'pacientes', 'sedes', ['sede_id'], ['id'])
    op.add_column('profesionales', sa.Column('sede_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_profesionales_sede_id'), 'profesionales', ['sede_id'], unique=False)
    op.create_foreign_key(None, 'profesionales', 'sedes', ['sede_id'], ['id'])
    op.add_column('promo_promociones', sa.Column('sede_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_promo_promociones_sede_id'), 'promo_promociones', ['sede_id'], unique=False)
    op.create_foreign_key(None, 'promo_promociones', 'sedes', ['sede_id'], ['id'])
    op.alter_column('sedes', 'margen_local',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('turnos', sa.Column('sede_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_turnos_sede_id'), 'turnos', ['sede_id'], unique=False)
    op.create_foreign_key(None, 'turnos', 'sedes', ['sede_id'], ['id'])
    op.drop_constraint(op.f('fk_usuarios_profesional'), 'usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'usuarios', 'profesionales', ['profesional_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.create_foreign_key(op.f('fk_usuarios_profesional'), 'usuarios', 'profesionales', ['profesional_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'turnos', type_='foreignkey')
    op.drop_index(op.f('ix_turnos_sede_id'), table_name='turnos')
    op.drop_column('turnos', 'sede_id')
    op.alter_column('sedes', 'margen_local',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.drop_constraint(None, 'promo_promociones', type_='foreignkey')
    op.drop_index(op.f('ix_promo_promociones_sede_id'), table_name='promo_promociones')
    op.drop_column('promo_promociones', 'sede_id')
    op.drop_constraint(None, 'profesionales', type_='foreignkey')
    op.drop_index(op.f('ix_profesionales_sede_id'), table_name='profesionales')
    op.drop_column('profesionales', 'sede_id')
    op.drop_constraint(None, 'pacientes', type_='foreignkey')
    op.drop_index(op.f('ix_pacientes_sede_id'), table_name='pacientes')
    op.drop_column('pacientes', 'sede_id')
    op.drop_constraint(None, 'inv_movimientos', type_='foreignkey')
    op.drop_index(op.f('ix_inv_movimientos_sede_id'), table_name='inv_movimientos')
    op.drop_column('inv_movimientos', 'sede_id')
    op.drop_constraint(None, 'inv_compras', type_='foreignkey')
    op.drop_constraint('uq_inv_compras_clinica_sede_doc_numero', 'inv_compras', type_='unique')
    op.drop_index(op.f('ix_inv_compras_sede_id'), table_name='inv_compras')
    op.create_index(op.f('uq_inv_compras_clinica_doc_numero'), 'inv_compras', ['clinica_id', 'tipo_doc', 'numero'], unique=True)
    op.drop_column('inv_compras', 'sede_id')
    op.drop_constraint(None, 'comprobantes', type_='foreignkey')
    op.drop_index(op.f('ix_comprobantes_sede_id'), table_name='comprobantes')
    op.drop_column('comprobantes', 'sede_id')
    op.alter_column('clinicas', 'margen_global',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False,
               existing_server_default=sa.text("'50'"))
    op.drop_constraint(None, 'cierres_caja', type_='foreignkey')
    op.drop_constraint('uq_cierres_caja_clinica_sede_fecha', 'cierres_caja', type_='unique')
    op.drop_index(op.f('ix_cierres_caja_sede_id'), table_name='cierres_caja')
    op.create_index(op.f('uq_cierres_caja_clinica_fecha'), 'cierres_caja', ['clinica_id', 'fecha'], unique=True)
    op.drop_column('cierres_caja', 'sede_id')
    op.drop_constraint(None, 'caja_movimientos', type_='foreignkey')
    op.drop_index(op.f('ix_caja_movimientos_sede_id'), table_name='caja_movimientos')
    op.drop_column('caja_movimientos', 'sede_id')
    # ### end Alembic commands ###
