"""add_sede_id_to_notas_clinicas_and_deudas_paciente

Revision ID: 7996301d409a
Revises: 7f44c0f7f40f
Create Date: 2026-05-26 02:32:08.955738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7996301d409a'
down_revision: Union[str, Sequence[str], None] = '7f44c0f7f40f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deudas_paciente', sa.Column('sede_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_deudas_paciente_sede_id'), 'deudas_paciente', ['sede_id'], unique=False)
    op.create_foreign_key(None, 'deudas_paciente', 'sedes', ['sede_id'], ['id'])
    op.add_column('notas_clinicas', sa.Column('sede_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notas_clinicas_sede_id'), 'notas_clinicas', ['sede_id'], unique=False)
    op.create_foreign_key(None, 'notas_clinicas', 'sedes', ['sede_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notas_clinicas', type_='foreignkey')
    op.drop_index(op.f('ix_notas_clinicas_sede_id'), table_name='notas_clinicas')
    op.drop_column('notas_clinicas', 'sede_id')
    op.drop_constraint(None, 'deudas_paciente', type_='foreignkey')
    op.drop_index(op.f('ix_deudas_paciente_sede_id'), table_name='deudas_paciente')
    op.drop_column('deudas_paciente', 'sede_id')
    # ### end Alembic commands ###
