"""add_sede_id_to_servicios_productos_proveedores

Revision ID: 7f44c0f7f40f
Revises: 6630f666db80
Create Date: 2026-05-26 02:10:11.523860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f44c0f7f40f'
down_revision: Union[str, Sequence[str], None] = '6630f666db80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inv_productos', sa.Column('sede_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('uq_inv_productos_clinica_sku'), table_name='inv_productos')
    op.create_index(op.f('ix_inv_productos_sede_id'), 'inv_productos', ['sede_id'], unique=False)
    op.create_unique_constraint('uq_inv_productos_clinica_sede_sku', 'inv_productos', ['clinica_id', 'sede_id', 'sku'])
    op.create_foreign_key(None, 'inv_productos', 'sedes', ['sede_id'], ['id'])
    op.add_column('inv_proveedores', sa.Column('sede_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('uq_inv_proveedores_clinica_nombre'), table_name='inv_proveedores')
    op.create_index(op.f('ix_inv_proveedores_sede_id'), 'inv_proveedores', ['sede_id'], unique=False)
    op.create_unique_constraint('uq_inv_proveedores_clinica_sede_nombre', 'inv_proveedores', ['clinica_id', 'sede_id', 'nombre'])
    op.create_foreign_key(None, 'inv_proveedores', 'sedes', ['sede_id'], ['id'])
    op.add_column('servicios', sa.Column('sede_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_servicios_sede_id'), 'servicios', ['sede_id'], unique=False)
    op.create_foreign_key(None, 'servicios', 'sedes', ['sede_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servicios', type_='foreignkey')
    op.drop_index(op.f('ix_servicios_sede_id'), table_name='servicios')
    op.drop_column('servicios', 'sede_id')
    op.drop_constraint(None, 'inv_proveedores', type_='foreignkey')
    op.drop_constraint('uq_inv_proveedores_clinica_sede_nombre', 'inv_proveedores', type_='unique')
    op.drop_index(op.f('ix_inv_proveedores_sede_id'), table_name='inv_proveedores')
    op.create_index(op.f('uq_inv_proveedores_clinica_nombre'), 'inv_proveedores', ['clinica_id', 'nombre'], unique=True)
    op.drop_column('inv_proveedores', 'sede_id')
    op.drop_constraint(None, 'inv_productos', type_='foreignkey')
    op.drop_constraint('uq_inv_productos_clinica_sede_sku', 'inv_productos', type_='unique')
    op.drop_index(op.f('ix_inv_productos_sede_id'), table_name='inv_productos')
    op.create_index(op.f('uq_inv_productos_clinica_sku'), 'inv_productos', ['clinica_id', 'sku'], unique=True)
    op.drop_column('inv_productos', 'sede_id')
    # ### end Alembic commands ###
