"""initial_schema

Revision ID: b4e0bae1abcd
Revises: 
Create Date: 2026-05-22 18:06:24.868149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b4e0bae1abcd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profesionales', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('profesionales', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_profesionales_dni'), table_name='profesionales')
    op.create_index(op.f('ix_profesionales_dni'), 'profesionales', ['dni'], unique=False)
    op.drop_index(op.f('ix_profesionales_matricula'), table_name='profesionales')
    op.create_index(op.f('ix_profesionales_matricula'), 'profesionales', ['matricula'], unique=False)
    op.create_index(op.f('ix_profesionales_created_at'), 'profesionales', ['created_at'], unique=False)
    op.create_index(op.f('ix_profesionales_deleted_at'), 'profesionales', ['deleted_at'], unique=False)
    op.alter_column('servicios', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('servicios', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('servicios', 'precio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('servicios', 'duracion_min',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_servicios_created_at'), 'servicios', ['created_at'], unique=False)
    op.create_index(op.f('ix_servicios_deleted_at'), 'servicios', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servicios_deleted_at'), table_name='servicios')
    op.drop_index(op.f('ix_servicios_created_at'), table_name='servicios')
    op.alter_column('servicios', 'duracion_min',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('servicios', 'precio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('servicios', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('servicios', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_profesionales_deleted_at'), table_name='profesionales')
    op.drop_index(op.f('ix_profesionales_created_at'), table_name='profesionales')
    op.drop_index(op.f('ix_profesionales_matricula'), table_name='profesionales')
    op.create_index(op.f('ix_profesionales_matricula'), 'profesionales', ['matricula'], unique=True)
    op.drop_index(op.f('ix_profesionales_dni'), table_name='profesionales')
    op.create_index(op.f('ix_profesionales_dni'), 'profesionales', ['dni'], unique=True)
    op.alter_column('profesionales', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('profesionales', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
